# Site settings
title: Diego A. Rueda
description: 'Presentation WebPage'
url: 'http://dandrue.github.io'
baseurl: ''
profilepic: '/images/profile.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Diego A. Rueda'
  email: d.ruedaq@gmail.com
#  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  dandrue
  linkedin_username:  diego-a-rueda-7b36b821a/
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
