# Site settings
title: Diego A. Rueda
description: 'Presentation WebPage'
url: 'http://dandrue.github.io'
baseurl: ''
profilepic: '/images/profile.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'fontawesome/js/fontawesome.min.js'

author:
  name: 'Diego A. Rueda'
  email: d.ruedaq@gmail.com
  github_username: dandrue
  linkedin_username: diegoarueda

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
    - jekyll-seo-tag
exclude: ['README.md', 'screenshot-overview.png']
